### ISSUE TITLE
Psyco invalid dependency

### ISSUE THREAD

**Issue by blshkv** [inguma/bokken#12]
currently, bokken is checking that Psyco is installed from the dependecy_check script. 
However, I can't find any use of this outdated and unsupported library. 
Instead, the psycopg2 library seems used in the bokken/lib/web/db.py file. 

Perhaps, this is a typo. Please double check.

**Comment by Jo-Con-El** [comment]
You are right with Psyco.  But don't get confused. lib/web/* is part of webpy, and psycopg is the PostgreSQL connector, so that's a red herring.

For the *real* Psyco dependency, it was brought it by pyew.  The good news is that pyew support has been nuked in Mercurial already together with Psyco (see commit 5ffacff).

Thank you and keep using Bokken!
